name: cleoenv
channels:
    - conda-forge
dependencies:
    - python==3.9.9 # matches version of python used to make yac bindings on levante
    - doxygen>=1.10.0
    - pip
    - pip:
      - -r requirements.txt
